
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxviymjjibchtfmvtchu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4dml5bWpqaWJjaHRmbXZ0Y2h1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NjQ4ODEsImV4cCI6MjA1OTI0MDg4MX0.18rr2pEjbKCcchPmBk6rvpl-1h2A8vz5Yg7nj6Mazwo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
